# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
matrix:
  include:
    - name: Python 3.6
      python: 3.6
    - name: Python 3.7
      python: 3.7

install:
  - pip install -e .[test]
script:
  - pytest -s tests/
after_success:
  - pip install coveralls
  - coveralls
